import os


class Config():
  DATABASE_URL = os.environ.get('DATABASE_URL')
  APP_WEB_URL = os.environ.get('APP_WEB_URL')
  VERSION="v1"

  SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
  SQLALCHEMY_TRACK_MODIFICATIONS = False
  SQLALCHEMY_POOL_SIZE = 15
  SQLALCHEMY_MAX_OVERFLOW = 10
  SQLALCHEMY_POOL_RECYCLE = 60 * 60 * 2
  SQLALCHEMY_POOL_TIMEOUT = 30
